/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
          container: 'rgb(var(--color-primary-container) / <alpha-value>)',
          fixed: 'rgb(var(--color-primary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
          tint: 'rgb(var(--color-primary-tint) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary) / <alpha-value>)',
          container: 'rgb(var(--color-secondary-container) / <alpha-value>)',
          fixed: 'rgb(var(--color-secondary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
        },
        tertiary: {
          DEFAULT: 'rgb(var(--color-tertiary) / <alpha-value>)',
          container: 'rgb(var(--color-tertiary-container) / <alpha-value>)',
          fixed: 'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
          'fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        },
        error: {
          DEFAULT: 'rgb(var(--color-error) / <alpha-value>)',
          container: 'rgb(var(--color-error-container) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'rgb(var(--color-surface) / <alpha-value>)',
          dim: 'rgb(var(--color-surface-dim) / <alpha-value>)',
          bright: 'rgb(var(--color-surface-bright) / <alpha-value>)',
          'container-lowest': 'rgb(var(--color-surface-cl) / <alpha-value>)',
          'container-low': 'rgb(var(--color-surface-clo) / <alpha-value>)',
          container: 'rgb(var(--color-surface-c) / <alpha-value>)',
          'container-high': 'rgb(var(--color-surface-ch) / <alpha-value>)',
          'container-highest': 'rgb(var(--color-surface-chh) / <alpha-value>)',
          tint: 'rgb(var(--color-surface-tint) / <alpha-value>)',
        },
        on: {
          primary: 'rgb(var(--color-on-primary) / <alpha-value>)',
          'primary-container': 'rgb(var(--color-on-primary-c) / <alpha-value>)',
          'primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
          'secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
          secondary: 'rgb(var(--color-on-secondary) / <alpha-value>)',
          'secondary-container': 'rgb(var(--color-on-secondary-c) / <alpha-value>)',
          tertiary: 'rgb(var(--color-on-tertiary) / <alpha-value>)',
          'tertiary-container': 'rgb(var(--color-on-tertiary-c) / <alpha-value>)',
          error: 'rgb(var(--color-on-error) / <alpha-value>)',
          'error-container': 'rgb(var(--color-on-error-c) / <alpha-value>)',
          surface: 'rgb(var(--color-on-surface) / <alpha-value>)',
          'surface-variant': 'rgb(var(--color-on-surface-v) / <alpha-value>)',
          'tertiary-fixed': 'rgb(var(--color-on-tf) / <alpha-value>)',
          'tertiary-fixed-variant': 'rgb(var(--color-on-tfv) / <alpha-value>)',
        },
        outline: {
          DEFAULT: 'rgb(var(--color-outline) / <alpha-value>)',
          variant: 'rgb(var(--color-outline-v) / <alpha-value>)',
        },
        shadow: 'rgb(var(--color-shadow) / <alpha-value>)',
        'surface-tint': 'rgb(var(--color-surface-tint-sa) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-md': ['45px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-sm': ['36px', { lineHeight: '44px', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      borderRadius: {
        none: '0',
        xs: '2px',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '28px',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0px 12px 32px rgba(25, 28, 32, 0.06)',
        'ambient-lg': '0px 16px 40px rgba(25, 28, 32, 0.08)',
        'ambient-sm': '0px 8px 24px rgba(25, 28, 32, 0.04)',
      },
      backdropBlur: {
        glass: '24px',
      },
    },
  },
  plugins: [],
};
